version: '3.8'

services:
  ssbes_application:
    build:
      context: ./ssbes
      dockerfile: Dockerfile
    image: ssbes
    environment:
      SSBES_DB_HOSTNAME: ${SSBES_DB_HOSTNAME}
      SSBES_DB_NAME: ${SSBES_DB_NAME}
      SSBES_DB_PASSWORD: ${SSBES_DB_PASSWORD}
      SSBES_DB_URL: ${SSBES_DB_URL}
      SSBES_DB_USERNAME: ${SSBES_DB_USERNAME}
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:13.5
    environment:
      POSTGRES_USER: ${SSBES_DB_USERNAME}
      POSTGRES_PASSWORD: ${SSBES_DB_PASSWORD}
      POSTGRES_DB: ${SSBES_DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    ports:
      - 5435:5432

volumes:
  pgdata:
  pgconf:
  pglog:

