services:
  ssbes_application:
    build:
      context: ./ssbes
      dockerfile: Dockerfile
    image: ssbes
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:13.5
    environment:
      POSTGRES_USER: ${SSBES_DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${SSBES_DB_PASSWORD:-postgres}
      POSTGRES_DB: ${SSBES_DB_NAME:-ssbes}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    ports:
      - 5435:5432

volumes:
  pgdata:
  pgconf:
  pglog:
